### ISSUE TITLE
Part C Step 2

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/banking-digitalization-using-hybrid-cloud-with-mainframes#2]
https://github.com/IBM/banking-digitalization-using-hybrid-cloud-with-mainframes#2-make-a-cognitive-application-using-watson-services

Should this also be in the "EXTRA" part? It seems that it's also a "do it yourself" step like the IoT part.

**Comment by alexis-chretienne** [comment]
@AnthonyAmanse , 

No. At this step 2 ("Make a cognitive application using Watson Services"), developers know how to basically use Bluemix because of they successfully did the step 1 "Start with Node.js on Bluemix", which may be difficult for beginners. Indeed in this step 1, I gave directions but I ask developers to read the Bluemix documentation(for getting/pushing/deploying the Hello Worlds project). Learning how to read the Bluemix documentation is essential and necessary, that is why in step 2, I continue illustrating sub-steps but I want to focus on how to reach the right information in the Bluemix documentation . Using Watson services is easy. Learn how to read the documentation may be challenging. The objective of this documentation training for developers is to let them go on Bluemix after this journey, like described in the "Extra" Part, where in developers are totally independent :).
